---
- name: Deploy SSL certs to control node
  hosts: servers  # This targets the 'servers' group from your inventory
  gather_facts: yes  # Optional: If you need system facts (like OS version) for your tasks

  tasks:
    - name: Ensure the directory for SSL certificates exists
      file:
        path: /etc/ssl/certs
        state: directory
        mode: '0755'

    - name: Deploy SSL certificate
      copy:
        src: /path/to/cert  # Specify the path to your certificate file
        dest: /etc/ssl/certs/my_cert.crt  # Destination path on the target machine
        owner: root
        group: root
        mode: '0644'

    - name: Deploy SSL private key
      copy:
        src: /path/to/private_key  # Specify the path to your private key file
        dest: /etc/ssl/private/my_private_key.key  # Destination path on the target machine
        owner: root
        group: root
        mode: '0600'
        
    - name: Reload the service using the SSL certificate (example: nginx)
      service:
        name: nginx  # Replace with your actual service (e.g., apache2, nginx)
        state: reloaded
