---
- name: Deploy SSL certs to control node
  hosts: servers
  gather_facts: yes

  tasks:
    - name: Ensure the directory for SSL certificates exists
      file:
        path: /etc/ssl/certs
        state: directory
        mode: '0755'

    - name: Deploy SSL certificate
      copy:
        src: /path/to/certs/my_cert.crt  # Update this path to the correct location of your certificate file
        dest: /etc/ssl/certs/my_cert.crt
        owner: root
        group: root
        mode: '0644'

    - name: Deploy SSL private key
      copy:
        src: /path/to/private_key/my_private_key.key  # Update this path to the correct location of your private key file
        dest: /etc/ssl/private/my_private_key.key
        owner: root
        group: root
        mode: '0600'

    - name: Reload the service using the SSL certificate
      service:
        name: nginx  # Replace with your actual service (e.g., apache2, nginx)
        state: reloaded
