---
- name: Simple CA Setup on Control Node
  hosts: control_node
  become: true
  tasks:
    - name: Install OpenSSL
      apt:
        name: openssl
        state: present
      when: ansible_os_family == "Debian"

    - name: Create CA directories
      file:
        path: "/etc/ssl/myCA/{{ item }}"
        state: directory
        mode: "{{ '0700' if item == 'private' else '0755' }}"
      loop:
        - ""
        - certs
        - crl
        - newcerts
        - private

    - name: Create CA files
      copy:
        content: "{{ item.content }}"
        dest: "/etc/ssl/myCA/{{ item.name }}"
      loop:
        - { name: "index.txt", content: "" }
        - { name: "serial", content: "1000" }

    - name: Generate CA private key and self-signed cert
      command: >
        openssl req -x509 -newkey rsa:4096 -sha256 -days 3650
        -nodes -subj "/C=US/ST=State/L=City/O=Org/CN=ca.example.com"
        -keyout /etc/ssl/myCA/private/cakey.pem
        -out /etc/ssl/myCA/certs/cacert.pem
      args:
        creates: /etc/ssl/myCA/certs/cacert.pem
